import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState, type ReactNode } from "react";
import { BarChart3, BookOpen, Clock3, Target, TrendingUp, ChevronLeft } from "lucide-react";
import { performance, performanceLabel } from "../lib/studyEngine";
export const Route=createFileRoute("/desempenho")({component:PerformancePage});
type R={date:string;subject:string;topic:string;minutes:number;correct:number;wrong:number};
const read=<T,>(k:string,f:T):T=>{try{return JSON.parse(localStorage.getItem(k)||"null")??f}catch{return f}};
const base:R[]=[{date:"2026-09-12",subject:"Português",topic:"Pronomes",minutes:90,correct:14,wrong:6},{date:"2026-09-13",subject:"Legislação",topic:"LEP",minutes:75,correct:15,wrong:5},{date:"2026-09-13",subject:"Informática",topic:"Segurança",minutes:45,correct:8,wrong:12}];
function PerformancePage(){const[records]=useState<R[]>(()=>read("estuda-study-records",base));const[filter,setFilter]=useState("Todas");const subjects=useMemo(()=>Array.from(new Set(records.map(r=>r.subject))),[records]);const f=filter==="Todas"?records:records.filter(r=>r.subject===filter);const min=f.reduce((n,r)=>n+r.minutes,0),c=f.reduce((n,r)=>n+r.correct,0),w=f.reduce((n,r)=>n+r.wrong,0),acc=performance(c,w);const rows=subjects.map(s=>{const a=records.filter(r=>r.subject===s),c=a.reduce((n,r)=>n+r.correct,0),w=a.reduce((n,r)=>n+r.wrong,0);return{s,acc:performance(c,w),min:a.reduce((n,r)=>n+r.minutes,0),q:c+w}}).sort((a,b)=>a.acc-b.acc);return <div className="min-h-screen bg-[#f7f8f7] text-[#14231d]"><div className="mx-auto max-w-[1180px] px-4 py-6 sm:px-6"><button onClick={()=>history.back()} className="mb-5 flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-[#64726a]"><ChevronLeft size={15}/> Voltar</button><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="flex items-center gap-2 text-[10px] font-black uppercase tracking-[.22em] text-[#08754f]"><BarChart3 size={14}/> Analytics de estudo</div><h1 className="mt-2 text-3xl font-black tracking-[-.045em]">Desempenho</h1><p className="mt-1 text-sm text-[#78847d]">Onde seu tempo está virando resultado — e onde ainda existe déficit.</p></div><select value={filter} onChange={e=>setFilter(e.target.value)} className="rounded-xl border border-[#dfe6e1] bg-white px-4 py-2.5 text-xs font-bold">{["Todas",...subjects].map(x=><option key={x}>{x}</option>)}</select></div><div className="mt-6 grid gap-3 sm:grid-cols-3"><Stat icon={<Clock3 size={16}/>} label="Tempo estudado" value={`${Math.floor(min/60)}h ${min%60}m`}/><Stat icon={<Target size={16}/>} label="Questões" value={String(c+w)}/><Stat icon={<TrendingUp size={16}/>} label="Aproveitamento" value={`${acc}%`}/></div><section className="mt-5 rounded-[22px] border border-[#dfe7e2] bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><BookOpen size={17} className="text-[#08754f]"/><h2 className="text-sm font-black">Performance por matéria</h2></div><div className="mt-5 space-y-3">{rows.map(x=><div key={x.s} className="rounded-xl bg-[#f7f9f8] p-4"><div className="flex items-center justify-between"><span className="text-[11px] font-black">{x.s}</span><span className="text-[10px] font-black text-[#08754f]">{x.acc}% · {performanceLabel(x.acc)}</span></div><div className="mt-2 h-2 rounded-full bg-[#e3e9e5]"><div className="h-full rounded-full bg-[#15956b]" style={{width:`${x.acc}%`}}/></div><div className="mt-2 flex justify-between text-[8px] font-bold text-[#8a958f]"><span>{x.q} questões</span><span>{x.min} min</span></div></div>)}</div></section></div></div>}
function Stat({icon,label,value}:{icon:ReactNode;label:string;value:string}){return <div className="rounded-[18px] border border-[#dfe7e2] bg-white p-5 shadow-sm"><div className="flex items-center gap-2 text-[#08754f]">{icon}<span className="text-[9px] font-black uppercase tracking-widest text-[#7a877f]">{label}</span></div><div className="mt-2 text-2xl font-black">{value}</div></div>}
