import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { BarChart3, BookOpen, CalendarDays, Check, Clock3, Flame, LayoutDashboard, Menu, Play, Plus, Target, TrendingUp, Upload, X } from "lucide-react";

export const Route = createFileRoute("/")({ component: Index });

type Page = "dashboard" | "plano" | "cronometro" | "desempenho" | "edital";

const subjects = [
  ["Português", 72, 78], ["Raciocínio Lógico", 68, 81], ["Informática", 41, 54],
  ["Legislação", 84, 76], ["Direito Constitucional", 36, 67], ["Direito Administrativo", 29, 50],
] as const;

const agenda = [
  ["SEG", "14", "Português", "Pronomes e colocação", true],
  ["TER", "15", "Raciocínio Lógico", "Proposições", true],
  ["QUA", "16", "Informática", "Arquitetura de computadores", false],
  ["QUI", "17", "Legislação", "LEP — revisão", false],
  ["SEX", "18", "Simulado", "40 questões", false],
] as const;

function Index() {
  const [page, setPage] = useState<Page>("dashboard");
  const [menu, setMenu] = useState(false);
  const [upload, setUpload] = useState(false);
  const [file, setFile] = useState("");
  const [seconds, setSeconds] = useState(0);
  const go = (p: Page) => { setPage(p); setMenu(false); };

  return <div className="min-h-screen bg-[#f6f5f1] text-[#17211b]">
    <style>{`body{margin:0;font-family:Inter,ui-sans-serif,system-ui,sans-serif}.app-grid{background-image:linear-gradient(rgba(23,33,27,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(23,33,27,.035) 1px,transparent 1px);background-size:28px 28px}`}</style>
    <aside className={`fixed inset-y-0 left-0 z-40 w-[260px] border-r border-[#dfe2dc] bg-[#fbfaf7] p-5 transition-transform lg:translate-x-0 ${menu ? "translate-x-0" : "-translate-x-full"}`}>
      <div className="flex h-full flex-col">
        <div className="flex items-center justify-between"><button onClick={() => go("dashboard")} className="flex items-center gap-3 text-left"><div className="flex h-10 w-10 items-center justify-center rounded-[14px] bg-[#0e5b3d]"><span className="text-lg font-black text-white">ET</span></div><div><div className="text-[19px] font-extrabold">Estuda Thê!</div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-[#7d877f]">Estudo bagual</div></div></button><button className="lg:hidden" onClick={() => setMenu(false)}><X size={20}/></button></div>
        <div className="mt-9 rounded-2xl border border-[#dfe2dc] bg-white p-4"><div className="text-[10px] font-bold uppercase tracking-widest text-[#8a938c]">Concurso ativo</div><div className="mt-2 font-bold">PPRS — Polícia Penal RS</div><div className="mt-3 h-1.5 rounded-full bg-[#e8ebe5]"><div className="h-full w-[61%] rounded-full bg-[#0e5b3d]"/></div><div className="mt-2 flex justify-between text-xs text-[#7d877f]"><span>61% do edital</span><span>61/100</span></div></div>
        <nav className="mt-7 space-y-1"><Nav active={page === "dashboard"} icon={<LayoutDashboard size={18}/>} text="Visão geral" click={() => go("dashboard")}/><Nav active={page === "plano"} icon={<CalendarDays size={18}/>} text="Plano de estudo" click={() => go("plano")}/><Nav active={page === "cronometro"} icon={<Clock3 size={18}/>} text="Horas líquidas" click={() => go("cronometro")}/><Nav active={page === "desempenho"} icon={<BarChart3 size={18}/>} text="Desempenho" click={() => go("desempenho")}/><Nav active={page === "edital"} icon={<BookOpen size={18}/>} text="Meu edital" click={() => go("edital")}/></nav>
        <div className="mt-auto rounded-2xl bg-[#123d2d] p-4 text-white"><div className="text-xs text-[#cbd9d1]">Meta da semana</div><div className="mt-1 text-2xl font-extrabold">18h</div><div className="mt-3 flex justify-between text-xs text-[#cbd9d1]"><span>12h42 estudadas</span><span>71%</span></div><div className="mt-2 h-1.5 rounded-full bg-white/15"><div className="h-full w-[71%] rounded-full bg-white"/></div></div>
      </div>
    </aside>
    {menu && <button aria-label="Fechar menu" onClick={() => setMenu(false)} className="fixed inset-0 z-30 bg-black/20 lg:hidden"/>}
    <main className="min-h-screen lg:pl-[260px]"><header className="sticky top-0 z-20 flex h-[72px] items-center justify-between border-b border-[#e0e2dc] bg-[#f6f5f1]/95 px-5 backdrop-blur md:px-8"><div className="flex items-center gap-3"><button className="rounded-xl border border-[#dfe2dc] bg-white p-2 lg:hidden" onClick={() => setMenu(true)}><Menu size={20}/></button><div className="text-sm font-semibold text-[#667069]">PPRS / <span className="text-[#17211b]">{title(page)}</span></div></div><button onClick={() => setUpload(true)} className="flex items-center gap-2 rounded-xl bg-[#0e5b3d] px-4 py-2.5 text-sm font-bold text-white"><Plus size={17}/><span className="hidden sm:inline">Novo edital</span></button></header>
      <div className="app-grid min-h-[calc(100vh-72px)] px-5 py-7 md:px-8 md:py-9">{page === "dashboard" && <Dashboard upload={() => setUpload(true)} go={go}/>} {page === "plano" && <Plan/>} {page === "cronometro" && <Timer seconds={seconds} setSeconds={setSeconds}/>} {page === "desempenho" && <Performance/>} {page === "edital" && <Edital file={file} upload={() => setUpload(true)}/>}</div></main>
    {upload && <Modal file={file} setFile={setFile} close={() => setUpload(false)}/>}</div>;
}

function title(p: Page) { return ({dashboard:"Visão geral",plano:"Plano de estudo",cronometro:"Horas líquidas",desempenho:"Desempenho",edital:"Meu edital"})[p]; }
function Nav({active,icon,text,click}:{active:boolean;icon:React.ReactNode;text:string;click:()=>void}) { return <button onClick={click} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${active?"bg-[#e5eee9] text-[#0e5b3d]":"text-[#68726b] hover:bg-[#f0f1ed]"}`}>{icon}{text}</button>; }
function Section({eyebrow,text}:{eyebrow?:string;text:string}) { return <div className="mb-5">{eyebrow&&<div className="mb-1 text-[10px] font-extrabold uppercase tracking-[.2em] text-[#8b948e]">{eyebrow}</div>}<h2 className="m-0 text-xl font-extrabold tracking-tight md:text-2xl">{text}</h2></div>; }
function Stat({icon,label,value,sub}:{icon:React.ReactNode;label:string;value:string;sub:string}) { return <div className="rounded-2xl border border-[#dfe2dc] bg-white p-5"><div className="flex justify-between"><div className="text-xs font-bold uppercase tracking-wider text-[#7e8881]">{label}</div><div className="text-[#0e5b3d]">{icon}</div></div><div className="mt-4 text-2xl font-black">{value}</div><div className="mt-1 text-xs text-[#7e8881]">{sub}</div></div>; }
function Dashboard({upload,go}:{upload:()=>void;go:(p:Page)=>void}) { return <div className="mx-auto max-w-[1320px]"><div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-sm font-bold text-[#0e5b3d]"><span className="h-2 w-2 rounded-full bg-[#0e5b3d]"/> Terça-feira, 15 de setembro</div><h1 className="text-3xl font-black tracking-[-.04em] md:text-4xl">Bora estudar, Pedro.</h1><p className="mt-2 text-sm text-[#68726b] md:text-base">Seu estudo, organizado. Seu concurso, mais perto.</p></div><button onClick={upload} className="flex w-fit items-center gap-2 rounded-xl border border-[#d8ddd6] bg-white px-4 py-3 text-sm font-bold"><Upload size={17}/> Importar edital PDF</button></div>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={<Flame size={20}/>} label="Constância" value="7 dias" sub="melhor: 12 dias"/><Stat icon={<Clock3 size={20}/>} label="Horas na semana" value="12h42" sub="meta: 18h00"/><Stat icon={<Target size={20}/>} label="Questões" value="187" sub="72% de acerto"/><Stat icon={<TrendingUp size={20}/>} label="Desempenho" value="72%" sub="+6% nesta semana"/></div>
  <div className="mt-8 grid gap-6 xl:grid-cols-[1.5fr_1fr]"><section className="rounded-2xl border border-[#dfe2dc] bg-white p-5 md:p-6"><Section eyebrow="Rotina" text="Agenda da semana"/><div className="space-y-2">{agenda.map(a=><div key={a[0]} className={`flex items-center gap-4 rounded-xl border p-3 ${a[4]?"border-[#dbe7df] bg-[#f5faf7]":"border-[#e7e9e4]"}`}><div className="w-12 text-center"><div className="text-[9px] font-extrabold text-[#8a938c]">{a[0]}</div><div className="text-lg font-black">{a[1]}</div></div><div className="h-9 w-px bg-[#e0e3de]"/><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{a[2]}</div><div className="truncate text-xs text-[#7b857e]">{a[3]}</div></div>{a[4]?<span className="flex h-7 w-7 items-center justify-center rounded-full bg-[#dcece3] text-[#0e5b3d]"><Check size={15}/></span>:<button onClick={()=>go("cronometro")} className="flex items-center gap-1 rounded-lg bg-[#edf3ef] px-3 py-2 text-xs font-bold text-[#0e5b3d]">Estudar <Play size={12} fill="currentColor"/></button>}</div>)}</div></section>
  <section className="rounded-2xl bg-[#123d2d] p-6 text-white"><div className="text-[10px] font-extrabold uppercase tracking-[.2em] text-[#b8ccc1]">Progresso geral</div><div className="mt-2 text-4xl font-black">61%</div><p className="mt-1 text-sm text-[#c1d1c8]">do edital concluído</p><div className="mt-7 h-2 rounded-full bg-white/15"><div className="h-full w-[61%] rounded-full bg-white"/></div><div className="mt-7 grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/10 p-3"><div className="text-[10px] text-[#b8ccc1]">Assuntos</div><div className="mt-1 font-bold">42 / 69</div></div><div className="rounded-xl bg-white/10 p-3"><div className="text-[10px] text-[#b8ccc1]">Revisões</div><div className="mt-1 font-bold">18 / 27</div></div></div><button onClick={()=>go("edital")} className="mt-6 flex items-center gap-2 text-sm font-bold">Ver edital →</button></section></div>
  <section className="mt-8 rounded-2xl border border-[#dfe2dc] bg-white p-5 md:p-6"><Section eyebrow="Edital" text="Andamento por matéria"/><div className="grid gap-4 md:grid-cols-2">{subjects.slice(0,4).map(s=><Subject key={s[0]} name={s[0]} progress={s[1]} accuracy={s[2]}/>)}</div></section></div>; }
function Subject({name,progress,accuracy}:{name:string;progress:number;accuracy:number}) { return <div className="rounded-xl border border-[#e6e8e3] p-4"><div className="flex justify-between"><span className="text-sm font-bold">{name}</span><span className="text-xs font-bold text-[#0e5b3d]">{progress}%</span></div><div className="mt-3 h-2 rounded-full bg-[#e9ece7]"><div className="h-full rounded-full bg-[#0e5b3d]" style={{width:`${progress}%`}}/></div><div className="mt-2 text-xs text-[#7d877f]">{accuracy}% de acerto nas questões</div></div>; }
function Plan(){return <div className="mx-auto max-w-[1320px]"><Section eyebrow="Organização" text="Plano de estudo"/><div className="grid gap-4 lg:grid-cols-5">{agenda.map(a=><div key={a[0]} className="min-h-[250px] rounded-2xl border border-[#dfe2dc] bg-white p-4"><div className="text-[10px] font-black text-[#8b948e]">{a[0]}</div><div className="font-black">{a[1]} SET</div><div className="mt-5 rounded-xl bg-[#f1f5f2] p-3"><div className="text-sm font-bold">{a[2]}</div><div className="mt-1 text-xs text-[#7c867f]">{a[3]}</div><div className="mt-3 text-[10px] font-bold uppercase tracking-wider text-[#0e5b3d]">50 min</div></div></div>)}</div></div>}
function Timer({seconds,setSeconds}:{seconds:number;setSeconds:React.Dispatch<React.SetStateAction<number>>}){const h=Math.floor(seconds/3600).toString().padStart(2,"0"),m=Math.floor(seconds%3600/60).toString().padStart(2,"0"),s=(seconds%60).toString().padStart(2,"0");return <div className="mx-auto max-w-[900px]"><Section eyebrow="Foco" text="Horas líquidas"/><div className="rounded-3xl border border-[#dfe2dc] bg-white p-7 text-center md:p-12"><div className="mx-auto flex h-64 w-64 items-center justify-center rounded-full border-[12px] border-[#e7eee9] md:h-80 md:w-80"><div><Clock3 className="mx-auto text-[#0e5b3d]" size={26}/><div className="mt-3 font-mono text-4xl font-black">{h}:{m}:{s}</div><div className="mt-2 text-xs font-bold uppercase tracking-widest text-[#8a938c]">tempo líquido</div></div></div><div className="mt-8 flex justify-center gap-3"><button onClick={()=>setSeconds(v=>v+1)} className="flex items-center gap-2 rounded-xl bg-[#0e5b3d] px-5 py-3 font-bold text-white"><Play size={17} fill="currentColor"/> Iniciar estudo</button><button onClick={()=>setSeconds(0)} className="rounded-xl border border-[#dfe2dc] px-5 py-3 font-bold">Zerar</button></div></div></div>}
function Performance(){return <div className="mx-auto max-w-[1100px]"><Section eyebrow="Análise" text="Seu desempenho"/><div className="grid gap-4 sm:grid-cols-3"><Stat icon={<Target size={20}/>} label="Acerto geral" value="72%" sub="187 questões"/><Stat icon={<TrendingUp size={20}/>} label="Evolução" value="+6%" sub="últimos 7 dias"/><Stat icon={<Flame size={20}/>} label="Melhor matéria" value="81%" sub="Raciocínio Lógico"/></div><div className="mt-6 rounded-2xl border border-[#dfe2dc] bg-white p-6"><Section text="Performance por matéria"/>{subjects.map(s=><div key={s[0]} className="mb-5"><div className="mb-2 flex justify-between text-sm"><span className="font-bold">{s[0]}</span><span className="font-bold text-[#0e5b3d]">{s[2]}%</span></div><div className="h-3 rounded-full bg-[#e8ebe5]"><div className="h-full rounded-full bg-[#0e5b3d]" style={{width:`${s[2]}%`}}/></div><div className="mt-1 text-xs text-[#8a938c]">conteúdo em {s[1]}%</div></div>)}</div></div>}
function Edital({file,upload}:{file:string;upload:()=>void}){return <div className="mx-auto max-w-[1100px]"><Section eyebrow="Conteúdo" text="Meu edital"/><div className="rounded-2xl border border-[#dfe2dc] bg-white p-6"><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="font-black">{file||"PPRS — Polícia Penal RS"}</div><div className="text-sm text-[#7d877f]">69 assuntos • 61% concluído</div></div><button onClick={upload} className="flex items-center justify-center gap-2 rounded-xl border border-[#dfe2dc] px-4 py-2.5 text-sm font-bold"><Upload size={16}/> Importar PDF</button></div><div className="mt-8 space-y-4">{subjects.map(s=><Subject key={s[0]} name={s[0]} progress={s[1]} accuracy={s[2]}/>)}</div></div></div>}
function Modal({file,setFile,close}:{file:string;setFile:(x:string)=>void;close:()=>void}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#17211b]/45 p-4"><div className="w-full max-w-lg rounded-3xl bg-[#fbfaf7] p-6 shadow-2xl"><div className="flex justify-between"><div><div className="text-lg font-black">Importar edital</div><div className="mt-1 text-sm text-[#7d877f]">Envie o PDF e organize seu conteúdo.</div></div><button onClick={close}><X size={19}/></button></div><label className="mt-6 flex cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-[#cfd6d0] bg-white px-5 py-10 text-center"><Upload className="text-[#0e5b3d]" size={28}/><span className="mt-3 text-sm font-bold">Clique para selecionar o PDF</span><input type="file" accept="application/pdf" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)setFile(f.name)}}/></label>{file&&<div className="mt-4 rounded-xl bg-[#eaf1ec] p-3 text-sm font-semibold text-[#0e5b3d]">✓ {file}</div>}<button onClick={close} className="mt-5 w-full rounded-xl bg-[#0e5b3d] py-3 text-sm font-bold text-white">Continuar</button></div></div>}
